# Generated by Django 4.0.10 on 2023-02-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='purchased_by', through='profiles.Purchase', to='releases.release'),
        ),
    ]
