# Generated by Django 4.0.10 on 2023-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_labelband_img_id_labelband_name_labelband_url_and_more'),
        ('profiles', '0003_profile_name_profile_username_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_fans', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following_labelbands',
            field=models.ManyToManyField(blank=True, null=True, related_name='fans', to='releases.labelband'),
        ),
    ]
