# Generated by Django 4.0.10 on 2023-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_labelband_img_id_labelband_name_labelband_url_and_more'),
        ('profiles', '0004_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='following_fans',
            field=models.ManyToManyField(blank=True, related_name='followers', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following_labelbands',
            field=models.ManyToManyField(blank=True, related_name='fans', to='releases.labelband'),
        ),
    ]
