# Generated by Django 4.0.10 on 2023-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_followers_profile_following_fans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='img_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
