# Generated by Django 4.0.10 on 2023-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_purchase_unique_profile_release_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredProfile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
