# Generated by Django 4.0.10 on 2023-02-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelBand',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subclass', models.CharField(choices=[('a', 'album'), ('t', 'track')], default='a', max_length=1)),
                ('artist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='releases.labelband')),
                ('selling_artist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selling_releases', to='releases.labelband')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('release_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='releases.release')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='releases.release')),
            ],
            bases=('releases.release',),
        ),
    ]
