# Generated by Django 4.0.10 on 2023-02-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_labelband_img_id_labelband_name_labelband_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='item_id',
            new_name='id',
        ),
    ]
