# Generated by Django 4.0.10 on 2023-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_release_last_viewed_as_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='img_url',
        ),
        migrations.AddField(
            model_name='release',
            name='img_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
