# Generated by Django 4.0.10 on 2023-03-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_remove_release_img_url_release_img_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='selling_artist_id',
            new_name='selling_artist',
        ),
    ]
