# Generated by Django 4.0.10 on 2023-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_rename_artist_id_release_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelband',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
