version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DJANGO_CURRENT_ENVIRONMENT=dev
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    command: celery -A bandcamp_plus_plus worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: