# Generated by Django 4.0.10 on 2023-02-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='max_profile_depth',
            field=models.IntegerField(default=0),
        ),
    ]
