# Generated by Django 4.0.10 on 2023-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardsettings_max_profile_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='delay_time',
            field=models.FloatField(default=1.0),
        ),
    ]
