# Generated by Django 4.0.10 on 2023-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboardsettings_main_update_task_run_once'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='main_update_task_run_once',
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='main_update_last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
