# Generated by Django 4.0.10 on 2023-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_bin_releases_recentlabelbandrelease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='sort_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recentfanpurchase',
            name='most_recent_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recentfanpurchase',
            name='seen_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recentlabelbandrelease',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recentlabelbandrelease',
            name='seen_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='flag',
            field=models.CharField(choices=[('a', 'album'), ('t', 'track'), ('p', 'profile'), ('l', 'labelband'), ('o', 'other')], default='a', max_length=1),
        ),
    ]
