# Generated by Django 4.0.10 on 2023-03-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_remove_release_img_url_release_img_id'),
        ('bins', '0003_bin_date_updated_bin_name_bin_sort_key_issue_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseAcquiredOutsideBandcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release')),
            ],
        ),
    ]
