# Generated by Django 4.0.10 on 2023-03-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_ignoredprofile'),
        ('releases', '0006_rename_artist_id_release_artist_and_more'),
        ('bins', '0004_releaseacquiredoutsidebandcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredFollowers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recentfanpurchase',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', unique=True),
        ),
        migrations.AlterField(
            model_name='recentlabelbandrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', unique=True),
        ),
        migrations.AlterField(
            model_name='releaseacquiredoutsidebandcamp',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release', unique=True),
        ),
        migrations.CreateModel(
            name='NewFollowingLabelBands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.labelband', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewFollowingFans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', unique=True)),
            ],
        ),
    ]
