# Generated by Django 4.0.10 on 2023-03-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_rename_artist_id_release_artist_and_more'),
        ('profiles', '0009_ignoredprofile'),
        ('bins', '0005_ignoredfollowers_alter_recentfanpurchase_release_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IgnoredFollowers',
        ),
        migrations.AlterField(
            model_name='newfollowers',
            name='follower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='newfollowingfans',
            name='following_fan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='newfollowinglabelbands',
            name='following_fan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='releases.labelband'),
        ),
        migrations.AlterField(
            model_name='recentfanpurchase',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='releases.release'),
        ),
        migrations.AlterField(
            model_name='recentlabelbandrelease',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='releases.release'),
        ),
        migrations.AlterField(
            model_name='releaseacquiredoutsidebandcamp',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='releases.release'),
        ),
    ]
