# Generated by Django 4.0.10 on 2023-03-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_ignoredprofile'),
        ('bins', '0006_delete_ignoredfollowers_alter_newfollowers_follower_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewFollowingFans',
            new_name='NewFollowingFans_Base',
        ),
        migrations.RemoveField(
            model_name='recentfanpurchase',
            name='seen_before',
        ),
        migrations.RemoveField(
            model_name='recentlabelbandrelease',
            name='seen_before',
        ),
        migrations.CreateModel(
            name='NewFollowingFans_Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_fan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
